/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "callback.h"

int * cout_1_svc(params * argp, struct svc_req * rqstp)
{
  static int result = 0;

  write(1,argp->data,strlen(argp->data));
	
  return &result;
}

int * cerr_1_svc(params * argp, struct svc_req * rqstp)
{
  static int result = 0;

  write(2,argp->data,strlen(argp->data));

  return &result;
}

int * ret_1_svc(int * argp, struct svc_req * rqstp)
{
  static int result = 0;

  exit(*argp);

  return &result;
}
