/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALLBACK_H_RPCGEN
#define _CALLBACK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct params {
	char *data;
	int seq;
};
typedef struct params params;

#define CALLBACK 0x20199276
#define V1 1

#if defined(__STDC__) || defined(__cplusplus)
#define cout 1
extern  int * cout_1(params *, CLIENT *);
extern  int * cout_1_svc(params *, struct svc_req *);
#define cerr 2
extern  int * cerr_1(params *, CLIENT *);
extern  int * cerr_1_svc(params *, struct svc_req *);
#define ret 3
extern  int * ret_1(int *, CLIENT *);
extern  int * ret_1_svc(int *, struct svc_req *);
extern int callback_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define cout 1
extern  int * cout_1();
extern  int * cout_1_svc();
#define cerr 2
extern  int * cerr_1();
extern  int * cerr_1_svc();
#define ret 3
extern  int * ret_1();
extern  int * ret_1_svc();
extern int callback_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_params (XDR *, params*);

#else /* K&R C */
extern bool_t xdr_params ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALLBACK_H_RPCGEN */
