/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "remote_exec.h"

int link[2];

int * rexec_1_svc(rexec_params * argp, struct svc_req * rqstp)
{
  static int result = 0;

  printf("rexec_1_svc: %s",argp->name);
  arg * pp = argp->first;
  while(pp != NULL)
    {
      printf(" %s",pp->val);
      pp = pp->next;
    }
  printf("\n");

  wait();
  /* close(link[0]); */
  /* close(link[1]); */
  pipe(link);

  if(fork())			/* parent */
    {
      close(link[0]);
    }
  else				/* child */
    {
      dup2(link[0],0);
      close(link[1]);

      int argc = 4;			/* because we need command, host and NULL at the end */
      arg * p = argp->first;
      while(p != NULL)
  	{
  	  p = p->next;
  	  argc++;
  	}

      SVCXPRT *transp = rqstp->rq_xprt; 
      /* struct netbuf *caller = (struct netbuf *)(svc_getrpccaller(transp);  */
      /* struct sockaddr_in *client_addr = (struct sockaddr_in *)(caller->buf);  */
      /* char *client_netaddr=inet_ntoa(client_addr->sin_addr); */
      /* printf("--->%s\n",client_addr); */
      printf("--->%s\n",rqstp->rq_xprt->xp_raddr.sin_addr);


      char * argv[argc];
      argv[0] = "./callback_client";
      argv[1] = "127.0.0.1";
      argv[2] = argp->name;

      p = argp->first;
      int i;
      for(i = 3; i < argc - 1; i++)
  	{
  	  argv[i] = p->val;
  	  p = p->next;
  	}
      argv[argc-1] = NULL;

      execv("./callback_client",argv);
    }

  return &result;
}

int * cin_1_svc(cin_params * argp, struct svc_req * rqstp)
{
  static int result = 0;

  printf("cin_1_svc: %d %s\n",argp->seq,argp->data);
  if(!strcmp(argp->data,""))
    close(link[1]);
  write(link[1],argp->data,strlen(argp->data));

  return &result;
}
