/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "remote_exec.h"

bool_t
xdr_arg (XDR *xdrs, arg *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->val, ~0))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (arg), (xdrproc_t) xdr_arg))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_rexec_params (XDR *xdrs, rexec_params *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->first, sizeof (arg), (xdrproc_t) xdr_arg))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cin_params (XDR *xdrs, cin_params *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->data, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->seq))
		 return FALSE;
	return TRUE;
}
