/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "remote_exec.h"


void
remote_exec_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	rexec_params  rexec_1_arg;
	rexec_1_arg.name = "xxx";
	rexec_1_arg.first = NULL;
	int  *result_2;
	cin_params  cin_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, REMOTE_EXEC, V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = rexec_1(&rexec_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = cin_1(&cin_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	remote_exec_1 (host);
exit (0);
}
